name: Deploy Firebase Functions

on:
  push:
    branches:
      - main # Or your default branch name
    paths:
      - 'functions/**' # Only run when code in the functions folder changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm --prefix functions install

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          action: deploy
          project_id: 'laughing-octo-winner'
          only: 'functions'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
